name: ci

on:
    push:
        branches:
            - "main"

jobs:
    docker:
        runs-on: ubuntu-latest
        env:
            ARTEMIS_VERSION: 2.42.0
            ARTCODED_VERSION: 2026.0.0
            KEYCLOAK_VERSION: 25.0.3
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push Docker image
              run: |
                  cd artemis-docker
                  bash prepare-docker.sh --from-release --artemis-version $ARTEMIS_VERSION
                  cd ./_TMP_/artemis/$ARTEMIS_VERSION                                                            
                  docker buildx build --push --platform linux/amd64,linux/arm64 \
                      --build-arg KEYCLOAK_VERSION=${{ env.KEYCLOAK_VERSION }} \
                      -f ./docker/Dockerfile-openjdk-25 \
                      -t ${{ secrets.DOCKER_USERNAME }}/artemis:${{ env.ARTCODED_VERSION }} .
